### ISSUE TITLE
DLボタンが表示されない

### ISSUE THREAD

**Issue by iwayasan** [masteralice3104/nico_downloader#6]
いつも重宝させていただいております。導入の簡単さと機能のシンプルさがすごく好きです。
現在ニコニコのページを開いてもボタンが表示されなくなっています。
（再DLすると初期設定のボタンは出てくるのですが、設定後保存のボタンは表示されませんでした。）
Twitterやレビューなどに同じ症状になっている方が見られたのでこちらにコメントさせていただきました。
24/09/25の13時頃までは使えていました。
こういったコメントを残すのは初めてなので、もし不手際があれば申し訳ありません。
可能であれば対応していただけるととても嬉しいです。よろしくお願いします。

**Comment by Sypgy** [comment]
私も同じ現象を確認しました。
json.data.response.seriesがnullの動画をダウンロードするとき、エラーがあるように見えますよね。
シリーズがちゃんとある動画は問題なくDLができますので、デバッグするときに使用できる動画のリンクを残します。
https://www.nicovideo.jp/watch/sm44147714

**Comment by masteralice3104** [comment]
当該現象を確認しました。
シリーズが存在しない動画の情報を読み込んだ際にnicojson.jsのJsonToSeries()のエラー処理が抜けていたことが原因で落ちています。

- 対策として一時的に5.0.0.10にアップデートし以前の状態に戻しておりとりあえずの対応を行っています
- 5.0.0.11にて当該現象は修正されます

**Comment by masteralice3104** [comment]
アップデートをかけました。5.0.0.11以降で完全に不具合が修正されます。

**Comment by iwayasan** [comment]
迅速な対応ありがとうございます。問題なくDLできました。
これからも利用させていただきます、本当にありがとうございます！

**Comment by ghost** [comment]
5.0.0.10で問題なくダウンロード保存できたが、5.0.0.11ではダウンロードまでは進むが「まもなく保存完了」でストップしてしまい、保存ができない。

**Comment by masteralice3104** [comment]
> 5.0.0.10で問題なくダウンロード保存できたが、5.0.0.11ではダウンロードまでは進むが「まもなく保存完了」でストップしてしまい、保存ができない。
https://github.com/masteralice3104/nico_downloader/issues/7

こちらで対応します。

**Comment by masteralice3104** [comment]
json.data.response.ownerがnullになっている動画を発見したため5.0.0.12で修正いたします。
特殊な条件下でnullになるようです。

**Comment by ghost** [comment]
無事DLできるようになりました。対応ありがとうございました。
