### ISSUE TITLE
タグ未設定の動画がダウンロードできなくなった

### ISSUE THREAD

**Issue by hirohiro49** [masteralice3104/nico_downloader#9]
10月末頃から、タグが設定されていない動画で保存ボタンが表示されなくなりました。
タグ設定すれば解消されるので回避は可能です。

**Comment by hirohiro49** [comment]
時期は関係なくて、元からの事象のようです。
たまたま、立て続けに条件を満たす動画があり気づいたようです。

**Comment by masteralice3104** [comment]
タグを取得する部分にて落ちていることを確認しました。
5.0.0.15で修正されます。
